export const Ukrainian = {
    sidebar: {
        signOutBtn: 'Вийти',
        homeLnk: 'Головна',
        reportsLnk: 'Звіти',
        settingsLnk: 'Налаштування',
    },
    productsPage: {
        title: 'Товари',
    },
    reportsPage: {
        title: 'Звіти',
    },
    settingsPage: {
        title: 'Налаштування',
        languagePicker: 'Оберіть мову',
        themePicker: 'Оберіть тему',
        dark: 'Темна',
        light: 'Світла',
        english: 'Англійська',
        ukrainian: 'Українська',
    },
    productsTable: {
        productPhoto: 'фото',
        productName: 'назва',
        productDescription: 'опис',
        productPrice: 'ціна',
        actionsBtn: 'дії',
        actionEdit: 'Редагувати',
        actionDelete: 'Видалити',
        generateQrCodeBtn: 'Згенерувати Qr-Code',
        addProductBtn: 'Додати новий товар',
        error: 'Товари недоступні',
    },
    productModal: {
        closeBtn: 'Закрити',
        photoUrl: 'Фото (Url)',
        addMode: {
            title: 'Додати новий товар',
            nameInput: 'Введіть назву',
            descriptionInput: 'Введіть опис',
            priceInput: 'Введіть ціну',
            submitButton: 'Додати продукт',
        },
        editMode: {
            title: 'Редагувати товар',
            nameInput: 'Введіть назву',
            descriptionInput: 'Введіть опис',
            priceInput: 'Введіть ціну',
            submitButton: 'Реадагувати',
        },
    },
    reportsTable: {
        productPhoto: 'фото',
        buyer: 'покупець',
        buyerEmail: 'електронна пошта',
        purchaseTime: 'час покупки',
        productName: 'назва',
        productPrice: 'ціна',
        error: 'Звіти недоступні',
    },
}
